services:
  - type: worker
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8119884133:AAE1dSDOjMXxrr3bOA7rdZofbpmif1XK1cA
