services:
  - type: web
    name: telegram-video-downloader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        value: 8252054122:AAH6gKwR8QoqiFdH8syDTgEbR9vhWMdTBvc
      - key: PORT
        value: 8000
